import {Game, obstacles, distance} from './game.js';
import {inputKey, isGameKey} from './input.js';
const $=s=>document.querySelector(s), game=new Game(), canvas=$('#flat'),ctx=canvas.getContext('2d');
let view='iso',keys={},joy={x:0,y:0},held={interact:false,sprint:false},width=900,height=600,time=0,last=0,cameraAngle=0,three=null,loading=false;
const names={top:'2D / 全局视野',iso:'2.5D / 等距跟随',third:'3D / 第三人称'};
function resize(){const r=$('#stage').getBoundingClientRect();width=r.width;height=r.height;const d=Math.min(devicePixelRatio||1,2);canvas.width=width*d;canvas.height=height*d;ctx.setTransform(d,0,0,d,0,0);if(three){three.renderer.setSize(width,height);three.camera.aspect=width/height;three.camera.updateProjectionMatrix();}}
new ResizeObserver(resize).observe($('#stage'));
function clearInput(){keys={};held={interact:false,sprint:false};joy={x:0,y:0};$('#nub').style.transform='';}
window.addEventListener('blur',clearInput);document.addEventListener('visibilitychange',()=>{clearInput();last=0;});
window.addEventListener('keydown',e=>{const key=inputKey(e);if(isGameKey(key)){e.preventDefault();keys[key]=true;}});
window.addEventListener('keyup',e=>{const key=inputKey(e);if(isGameKey(key)){e.preventDefault();keys[key]=false;}});
for(const id of ['interact','sprint']){let el=$('#'+id);el.onpointerdown=e=>{el.setPointerCapture(e.pointerId);held[id]=true;};el.onpointerup=el.onpointercancel=()=>held[id]=false;}
let pointer=null;const stick=$('#stick');stick.onpointerdown=e=>{pointer=e.pointerId;stick.setPointerCapture(pointer);stickMove(e);};stick.onpointermove=e=>{if(pointer===e.pointerId)stickMove(e);};stick.onpointerup=stick.onpointercancel=()=>{pointer=null;joy={x:0,y:0};$('#nub').style.transform='';};
function stickMove(e){let r=stick.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,l=Math.hypot(x,y);if(l>32){x*=32/l;y*=32/l;}joy={x:x/32,y:y/32};$('#nub').style.transform=`translate(${x}px,${y}px)`;}
let drag=null;$('#stage').addEventListener('pointerdown',e=>{if(view==='third'&&(e.target===three?.renderer.domElement)){drag={id:e.pointerId,x:e.clientX};e.target.setPointerCapture(e.pointerId);}});$('#stage').addEventListener('pointermove',e=>{if(drag?.id===e.pointerId){cameraAngle-=(e.clientX-drag.x)*.007;drag.x=e.clientX;}});$('#stage').addEventListener('pointerup',()=>drag=null);$('#stage').addEventListener('pointercancel',()=>drag=null);
function settings(open){$('#settings').hidden=!open;$('#settingsButton').setAttribute('aria-expanded',String(open));clearInput();if(!open)$('#stage').focus({preventScroll:true});}
$('#settingsButton').onclick=()=>settings($('#settings').hidden);$('#closeSettings').onclick=()=>settings(false);
window.addEventListener('keydown',e=>{if(e.key==='Escape')settings($('#settings').hidden);});
function begin(){if(game.status!=='ready')game.reset();game.start();$('#overlay').style.display='none';settings(false);clearInput();}
$('#start').onclick=begin;$('#restart').onclick=()=>{game.reset();settings(false);clearInput();showOverlay();};$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('#stage').requestFullscreen();settings(false);}catch{game.message='当前浏览器不支持全屏，请横屏体验';}};
function showOverlay(){const status=game.status;$('#overlay').style.display='flex';$('#overlay h2').textContent=status==='won'?'成功逃脱':status==='lost'?'演练结束':'沉船林地';$('#overlay p:not(.eyebrow)').innerHTML=status==='ready'?'修理三台发电机，开启闸门逃脱。<br>追猎者会巡逻、发现你并绕障碍追击。':game.message+'<br>可换个视角再试一次。';$('#start').textContent=status==='ready'?'进入演练 ↗':'再试一次 ↗';}
document.querySelectorAll('[data-view]').forEach(btn=>btn.onclick=async()=>{let next=btn.dataset.view;if(next==='third'&&!three){if(loading)return;loading=true;game.message='正在加载 3D 渲染器…';try{await setupThree();}catch(e){game.message='3D 加载失败：请检查网络和 WebGL 支持；2D / 2.5D 仍可玩';$('#cameraHint').textContent=game.message;console.error(e);loading=false;return;}loading=false;}view=next;clearInput();document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('selected',b===btn));canvas.style.display=view==='third'?'none':'block';$('#webgl').style.display=view==='third'?'block':'none';$('#mode').textContent=names[view];$('#cameraHint').textContent=view==='third'?'拖动画面旋转镜头 · 移动随镜头方向':'可随时切换视角，保留对局';resize();settings(false);});
function project(x,y,z=0){if(view==='top'){let s=Math.min(width,height)/110;return {x:width/2+(x-50)*s,y:height/2+(y-50)*s-z*s,s};}let s=Math.min(width/62,height/45);return {x:width/2+((x-game.player.x)-(y-game.player.y))*.707*s,y:height*.59+((x-game.player.x)+(y-game.player.y))*.36*s-z*s,s};}
function poly(points,fill,stroke){ctx.beginPath();points.forEach(([x,y,z],i)=>{let p=project(x,y,z||0);if(i)ctx.lineTo(p.x,p.y);else ctx.moveTo(p.x,p.y);});ctx.closePath();ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=1;ctx.stroke();}}
function box(x,y,w,d,h,color){poly([[x-w/2,y-d/2,0],[x+w/2,y-d/2,0],[x+w/2,y+d/2,0],[x-w/2,y+d/2,0]],'#13231f');if(view==='iso'){poly([[x+w/2,y-d/2,0],[x+w/2,y+d/2,0],[x+w/2,y+d/2,h],[x+w/2,y-d/2,h]],'#303a32');poly([[x-w/2,y+d/2,0],[x+w/2,y+d/2,0],[x+w/2,y+d/2,h],[x-w/2,y+d/2,h]],'#4b5142');}poly([[x-w/2,y-d/2,h],[x+w/2,y-d/2,h],[x+w/2,y+d/2,h],[x-w/2,y+d/2,h]],color,'#a5b29c44');}
function ellipse(x,y,z,rx,ry,color){let p=project(x,y,z);ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(p.x,p.y,rx*p.s,ry*p.s,0,0,Math.PI*2);ctx.fill();}
function label(x,y,z,text,color='#d6ed91'){let p=project(x,y,z);ctx.font='10px monospace';ctx.textAlign='center';ctx.fillStyle=color;ctx.fillText(text,p.x,p.y);}
function actor(a,hunter){const p=project(a.x,a.y),s=p.s,walk=Math.sin(time*11)*.3;ellipse(a.x,a.y,0,1.3,.7,'#06121088');if(view==='top'){ellipse(a.x,a.y,0,1.15,1.15,hunter?'#c96855':'#d6ed91');ctx.strokeStyle=hunter?'#eba487':'#fff5bd';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x+Math.sin(a.angle)*s*2,p.y+Math.cos(a.angle)*s*2);ctx.stroke();}else{box(a.x-.45,a.y+walk,.45,.5,1.6,'#242f30');box(a.x+.45,a.y-walk,.45,.5,1.6,'#242f30');box(a.x,a.y,1.5,.8,2.7,hunter?'#b35b48':'#afc77d');ellipse(a.x,a.y,3.4,.6,.6,'#e7cba0');if(hunter)box(a.x+1.5,a.y,.25,.5,3.8,'#949a81');}if(hunter&&game.stun>0)label(a.x,a.y,5,'STUN');}
function drawFlat(){ctx.clearRect(0,0,width,height);ctx.fillStyle='#102725';ctx.fillRect(0,0,width,height);poly([[0,0],[100,0],[100,100],[0,100]],'#354436','#6e7850');for(let y=0;y<100;y+=5)for(let x=0;x<100;x+=5){let n=(x*31+y*17)%13;poly([[x,y],[x+5,y],[x+5,y+5],[x,y+5]],n<4?'#394936':'#344333');}poly([[0,47],[100,47],[100,53],[0,53]],'#615f45');poly([[47,0],[53,0],[53,100],[47,100]],'#5a5b43');for(let i=0;i<240;i++){let x=(i*37.17)%98+1,y=(i*19.33)%98+1;ellipse(x,y,0,.12,.12,'#a0a77844');}
game.generators.forEach((g,i)=>{ellipse(g.x,g.y,0,4,view==='top'?4:2,g.p>=100?'#d6ed9122':'#ecb47122');});let items=[...obstacles.map(o=>({...o,kind:o.type})),...game.generators.map((g,i)=>({...g,kind:'gen',i})),...game.pallets.map(p=>({...p,kind:'pallet'})),{...game.player,kind:'player'},{...game.hunter,kind:'hunter'}, {...game.exit,kind:'exit'}];items.sort((a,b)=>view==='iso'?a.x+a.y-b.x-b.y:a.y-b.y);for(const o of items){switch(o.kind){case 'tree':ellipse(o.x+1,o.y+1,0,4,view==='top'?3:1.8,'#0e1c1a66');if(view==='iso')box(o.x,o.y,.8,.8,5,'#736148');ellipse(o.x,o.y,view==='iso'?5:0,3.5,view==='top'?3.5:2.7,'#172f26');ellipse(o.x-1,o.y-.5,view==='iso'?7:0,2.7,view==='top'?2.7:2.3,'#345b3d');ellipse(o.x-1.2,o.y-1,view==='iso'?8:0,1.5,1.4,'#526d43');break;case 'ruin':box(o.x,o.y,7,4,4,'#7c7c60');box(o.x+1,o.y,2,4,5,'#8a896b');break;case 'gen':box(o.x,o.y,3,2.4,2.4,o.p>=100?'#a8be70':'#8d7250');box(o.x,o.y,1.5,1.5,3.2,'#323d34');label(o.x,o.y,view==='iso'?5:0,(o.p>=100?'✓ ':'G'+(o.i+1)+' ')+Math.floor(o.p)+'%',o.p>=100?'#d6ed91':'#ecb471');break;case 'pallet':box(o.x,o.y,6,1.3,o.down?.4:2.5,o.down?'#817556':'#b59b69');break;case 'player':actor(game.player,false);break;case 'hunter':actor(game.hunter,true);break;case 'exit':box(96,44,1.5,2,7,'#81866b');box(96,56,1.5,2,7,'#81866b');if(o.p<100)box(96,50,1,10,5,game.powered===3?'#b1b971':'#52574b');label(96,50,8,'EXIT '+Math.floor(o.p)+'%');}}
let vg=ctx.createRadialGradient(width/2,height/2,height*.18,width/2,height/2,height*.75);vg.addColorStop(0,'#0b1d1900');vg.addColorStop(1,'#061614bb');ctx.fillStyle=vg;ctx.fillRect(0,0,width,height);drawMinimap();}
function drawMinimap(){const s=1,w=100,x=width-w-14,y=height-w-65;ctx.fillStyle='#0c1d1bc9';ctx.fillRect(x,y,w,w);ctx.strokeStyle='#72836155';ctx.strokeRect(x,y,w,w);for(const o of obstacles){ctx.fillStyle='#4c5c45';ctx.fillRect(x+o.x-2,y+o.y-2,4,4);}for(const g of game.generators){ctx.fillStyle=g.p>=100?'#d6ed91':'#ecb471';ctx.fillRect(x+g.x-2,y+g.y-2,4,4);}ctx.fillStyle='#d6ed91';ctx.beginPath();ctx.arc(x+game.player.x,y+game.player.y,3,0,7);ctx.fill();ctx.fillStyle='#e78265';ctx.beginPath();ctx.arc(x+game.hunter.x,y+game.hunter.y,2.5,0,7);ctx.fill();ctx.fillStyle='#d6ed91';ctx.fillRect(x+95,y+44,3,12);}
async function setupThree(){const T=await import('https://cdn.jsdelivr.net/npm/three@0.170.0/build/three.module.js');const renderer=new T.WebGLRenderer({antialias:true,powerPreference:'low-power'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));renderer.setSize(width,height);renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;const scene=new T.Scene();scene.background=new T.Color('#172d30');scene.fog=new T.Fog('#172d30',25,85);const camera=new T.PerspectiveCamera(58,width/height,.1,150);scene.add(new T.HemisphereLight(0xd8e3c1,0x273833,2));const sun=new T.DirectionalLight(0xffddb0,2.7);sun.position.set(-25,55,20);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-60,right:60,top:60,bottom:-60});scene.add(sun);
function mesh(geo,color,x,y,z,parent=scene){const m=new T.Mesh(geo,new T.MeshStandardMaterial({color,roughness:.95,flatShading:true}));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function cube(x,y,z,w,h,d,color,parent){return mesh(new T.BoxGeometry(w,h,d),color,x,y,z,parent);}
cube(50,-.25,50,100,.5,100,0x42503b);cube(50,.01,50,100,.03,6,0x68674f);cube(50,.02,50,6,.03,100,0x62624a);
for(const o of obstacles){if(o.type==='tree'){mesh(new T.CylinderGeometry(.4,.7,5,6),0x75614a,o.x,2.5,o.y);mesh(new T.ConeGeometry(3.8,7,7),0x294e38,o.x,6,o.y);mesh(new T.ConeGeometry(2.8,5,7),0x48613d,o.x,9,o.y);}else{cube(o.x,2,o.y,7,4,4,0x777b64);cube(o.x+1,4.5,o.y,2,1,4,0x96947a);}}
for(let i=0;i<160;i++){const x=(i*31.13)%96+2,z=(i*17.43)%96+2;mesh(new T.ConeGeometry(.25,.7,3),0x61714b,x,.3,z);}
const generators=game.generators.map(g=>{let group=new T.Group();group.position.set(g.x,0,g.y);scene.add(group);cube(0,1,0,3,2,2.4,0x8d7250,group);cube(0,2.4,0,1.7,.8,1.6,0x343f3b,group);const lamp=cube(0,2.6,-.85,1,.25,.1,0xecb471,group);return lamp;});const pallets=game.pallets.map(p=>{let m=cube(p.x,1.5,p.y,6,3,.7,0xb59b69);return m;});cube(96,3.5,44,1.5,7,2,0x81866b);cube(96,3.5,56,1.5,7,2,0x81866b);cube(96,7,50,1.5,1,14,0x81866b);const gate=cube(96,2.5,50,1,5,10,0x657153);
function character(color,hunter){const group=new T.Group();scene.add(group);cube(0,1.9,0,1.1,1.3,.7,color,group);mesh(new T.IcosahedronGeometry(.48,1),0xe5c6a0,0,3,0,group);const legs=[cube(-.3,.65,0,.38,1.2,.4,0x263534,group),cube(.3,.65,0,.38,1.2,.4,0x263534,group)];cube(-.8,1.9,0,.3,1,.35,color,group);cube(.8,1.9,0,.3,1,.35,color,group);if(hunter){cube(1.1,1.5,0,.15,2.5,.15,0x7e624a,group);cube(1.4,2.6,0,.7,.6,.15,0xadb3a2,group);}return {group,legs};}const player=character(0xafc77d,false),hunter=character(0xb35b48,true);$('#webgl').appendChild(renderer.domElement);three={T,renderer,scene,camera,player,hunter,generators,pallets,gate};resize();}
function drawThree(dt){const {T,renderer,scene,camera,player,hunter,generators,pallets,gate}=three;for(const [visual,actor] of [[player,game.player],[hunter,game.hunter]]){visual.group.position.set(actor.x,0,actor.y);visual.group.rotation.y=actor.angle;const moving=game.status==='playing'&&(visual===hunter?game.stun===0:Math.hypot(input.x,input.y)>.1);visual.legs.forEach((l,i)=>l.rotation.x=moving?Math.sin(time*10+i*Math.PI)*.5:0);}generators.forEach((m,i)=>{m.material.color.set(game.generators[i].p>=100?0xd6ed91:0xecb471);m.material.emissive.copy(m.material.color);m.material.emissiveIntensity=.5;});pallets.forEach((m,i)=>{m.rotation.x=game.pallets[i].down?Math.PI/2:0;m.position.y=game.pallets[i].down?.4:1.5;});gate.position.y=2.5+game.exit.p/100*6;const target=new T.Vector3(game.player.x+Math.sin(cameraAngle)*12,10,game.player.y+Math.cos(cameraAngle)*12);camera.position.lerp(target,1-Math.exp(-dt*8));camera.lookAt(game.player.x,2,game.player.y);renderer.render(scene,camera);}
let input={x:0,y:0};function frame(t){let dt=last?Math.min((t-last)/1000,.05):.016;last=t;time+=dt;let x=(keys.d||keys.arrowright?1:0)-(keys.a||keys.arrowleft?1:0)+joy.x,y=(keys.s||keys.arrowdown?1:0)-(keys.w||keys.arrowup?1:0)+joy.y;if(view==='iso'){[x,y]=[(x+y)*.707,(y-x)*.707];}else if(view==='third'){[x,y]=[x*Math.cos(cameraAngle)+y*Math.sin(cameraAngle),y*Math.cos(cameraAngle)-x*Math.sin(cameraAngle)];}input={x,y,interact:keys.e||held.interact,sprint:keys.shift||held.sprint};if(!document.hidden&&$('#settings').hidden)game.update(dt,input);if(view==='third'&&three)drawThree(dt);else drawFlat();updateHUD();requestAnimationFrame(frame);}
let previousMessage='',messageUntil=0;
function updateHUD(){
  const near=game.nearby,close=near&&distance(near,game.player)<6,repairing=close&&near.type!=='pallet';
  $('#time').textContent=Math.floor(game.time/60).toString().padStart(2,'0')+':'+Math.floor(game.time%60).toString().padStart(2,'0');
  $('#count').textContent=game.powered===3?'电力已恢复 · 开启逃生闸门':'还需启动 '+(3-game.powered)+' 台发电机';
  $('#energy').textContent=Math.round(game.stamina)+'%';$('#energybar').style.width=game.stamina+'%';
  $('#health').textContent=game.health===2?'健康':game.health===1?'受伤':'倒地';$('#health').style.color=game.health===2?'#d6ed91':'#e78265';
  if(previousMessage!==game.message){previousMessage=game.message;messageUntil=time+3.5;$('#message').textContent=game.message;}
  $('#message').classList.toggle('visible',time<messageUntil&&game.status==='playing');
  $('#repairPanel').hidden=!repairing||game.status!=='playing';
  $('#repairLabel').firstChild.textContent=near?.type==='exit'?'开启闸门 ':'修理进度 ';
  $('#repair').textContent=repairing?Math.floor(near.ref.p)+'%':'—';$('#repairbar').style.width=repairing?near.ref.p+'%':'0%';
  const touch=matchMedia('(pointer:coarse)').matches,key=touch?'按住交互':'按住 E';
  $('#prompt').textContent=close?near.type==='pallet'?(touch?'点击交互放下木板':'[ E ] 放下木板'):near.type==='exit'?key+' 开门 · 保持静止':key+' 修理 · 保持静止':game.exit.p>=100?'穿过东侧出口':game.powered===3?'前往东侧闸门':'';
  $('.bottom').hidden=!$('#prompt').textContent||game.status!=='playing';
  $('#threat').textContent=game.stun>0?'追猎者已被眩晕':game.chasing?'危险 · 追猎者正在逼近':'';
  $('.threat').hidden=!$('#threat').textContent||game.status!=='playing';
  if(['lost','won'].includes(game.status)&&$('#overlay').style.display==='none')showOverlay();
}
resize();requestAnimationFrame(frame);
