export const SIZE=140;
export const distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
export function palletPose(p){const progress=p.down?1-(p.drop||0)/.4:0,angle=.18+Math.max(0,progress)*(Math.PI/2-.18);return {baseX:p.x-2,angle,length:4,tipX:p.x-2+4*Math.sin(angle),tipZ:4*Math.cos(angle)};}
export const characters=[
  {id:'courier',name:'林间信使',skill:'疾步',cooldown:5,description:'向面朝方向持续冲刺 0.8 秒，速度为普通移动的 2.6 倍。碰到墙体立即停止，不穿墙、不瞬移。',color:0xafc77d},
  {id:'warden',name:'守灯人',skill:'护光',cooldown:5,description:'展开持续 2 秒的护光，抵挡一次攻击。护光不会恢复伤势，也不提供位移。',color:0xe1ba74},
  {id:'mist',name:'雾行者',skill:'烟幕',cooldown:5,description:'在当前位置留下持续 4 秒的烟幕，遮断追猎者视线与追踪。近身仍可能受击。',color:0x8fbfc2},
  {id:'doctor',name:'医生',skill:'自愈',cooldown:5,description:'受伤时使用技能，原地治疗 3 秒恢复健康。移动、翻越或受击中断治疗；其他角色不能自愈。',color:0xe1ddd2}
];
export const obstacles=[[12,12],[23,17],[43,12],[66,12],[84,14],[12,38],[36,34],[61,30],[86,35],[18,62],[42,59],[67,63],[87,70],[12,87],[38,86],[62,88],[83,91]].map(([x,y],i)=>({x,y,r:2.8,type:'tree',h:7+i%4}));
// Window openings and pallet doorways share the exact gap geometry used by both renderers.
export const walls=[
  {x:45.5,y:27,w:6,d:1},{x:56.5,y:27,w:6,d:1},{x:42,y:33,w:1,d:13},{x:60,y:33,w:1,d:13},{x:44.5,y:39,w:6,d:1},{x:56,y:39,w:9,d:1},
  {x:18.5,y:69,w:6,d:1},{x:29.5,y:69,w:6,d:1},{x:15,y:75,w:1,d:13},{x:33,y:75,w:1,d:13},{x:18,y:81,w:7,d:1},{x:29,y:81,w:9,d:1},
  {x:73.5,y:57,w:6,d:1},{x:84.5,y:57,w:6,d:1},{x:70,y:63,w:1,d:13},{x:88,y:63,w:1,d:13},{x:73,y:69,w:7,d:1},{x:84,y:69,w:9,d:1}
];
obstacles.push(...[[103,19,4],[119,35,5],[109,63,3.5],[125,78,5],[100,105,4],[78,118,5],[47,113,3.5],[24,102,4],[121,119,6],[14,48,3]].map(([x,y,r])=>({x,y,r,type:'rock',h:r*.8})));
obstacles.push(...[[106,10],[131,23],[131,59],[101,89],[12,118],[35,128],[65,130],[94,131],[132,102]].map(([x,y])=>({x,y,r:2.8,type:'tree',h:8})));
walls.push(...[{x:103,y:43,w:15,d:1},{x:96,y:49,w:1,d:13},{x:106,y:55,w:12,d:1},{x:119,y:49,w:1,d:15},{x:114,y:94,w:18,d:1},{x:106,y:100,w:1,d:13},{x:120,y:107,w:15,d:1},{x:57,y:103,w:18,d:1},{x:48,y:109,w:1,d:13},{x:64,y:116,w:16,d:1},{x:29,y:115,w:12,d:1},{x:22,y:121,w:1,d:13}]);
export class Game{
  constructor(){this.characterId='courier';this.role='survivor';this.reset();}
  get controlled(){return this.role==='hunter'?this.hunter:this.player;}
  selectRole(role){if(this.status!=='ready'||!['survivor','hunter'].includes(role))return false;this.role=role;return true;}
  unstick(actor){if(!this.blocked(actor.x,actor.y))return;for(let radius=.5;radius<=8;radius+=.5){for(let i=0;i<24;i++){const angle=i*Math.PI/12,x=actor.x+Math.cos(angle)*radius,y=actor.y+Math.sin(angle)*radius;if(!this.blocked(x,y)){actor.x=x;actor.y=y;this.pathTimer=0;return;}}}}
  breakPallet(){const p=this.pallets.find(p=>p.down&&!p.broken&&distance(p,this.hunter)<4);if(!p)return false;if(!this.attack)this.beginAttack();return true;}
  beginAttack(){if(this.attack||this.stun>0||this.hunterAttackCooldown>0)return false;this.attack={phase:'windup',elapsed:0,angle:this.hunter.angle||0};this.message='监管者挥击';return true;}
  inAttackCone(target){const dx=target.x-this.hunter.x,dy=target.y-this.hunter.y,d=Math.hypot(dx,dy);return d<4.2&&(d<.5||(dx*Math.sin(this.attack.angle)+dy*Math.cos(this.attack.angle))/d>.35);}
  updateAttack(dt){if(!this.attack)return;if(this.stun>0){this.attack=null;return;}const a=this.attack;a.elapsed+=dt;if(a.phase==='windup'&&a.elapsed>=.55){let hit=false;const p=this.pallets.find(p=>p.down&&!p.broken&&this.inAttackCone(p));if(p){p.broken=true;p.down=false;this.pathTimer=0;this.message='挥击破坏木板';hit=true;}else if(this.inAttackCone(this.player)&&this.visible()&&this.invincible===0){this.stopDecode();if(this.shield>0){this.shield=0;this.message='护光抵挡攻击';}else{this.health--;this.vault=null;this.dashRemaining=0;this.healProgress=0;this.invincible=3;this.message=this.health?'受伤！短暂加速':'逃生者已倒地';if(this.health<=0)this.status='lost';}hit=true;}a.phase='recovery';a.elapsed=0;a.duration=hit?2.1:1.1;this.hunterAttackCooldown=a.duration;if(!hit)this.message='挥击落空';}else if(a.phase==='recovery'&&a.elapsed>=a.duration){this.attack=null;this.hunterAttackCooldown=0;}}
  get character(){return characters.find(c=>c.id===this.characterId)||characters[0];}
  selectCharacter(id){if(this.status!=='ready'||!characters.some(c=>c.id===id))return false;this.characterId=id;return true;}
  reset(){this.player={x:48,y:73,angle:0};this.hunter={x:12,y:20,angle:0};this.generators=[{x:20,y:44,p:0},{x:73,y:23,p:0},{x:76,y:78,p:0}];this.pallets=[{x:50,y:39,down:false,drop:0},{x:24,y:81,down:false,drop:0},{x:79,y:69,down:false,drop:0}];this.windows=[{x:51,y:27},{x:24,y:69},{x:79,y:57}];this.exit={x:96,y:50,p:0};this.health=2;this.healProgress=0;this.dashCooldown=0;this.dashFlash=0;this.dashRemaining=0;this.dashDirection=null;this.shield=0;this.smoke=null;this.vault=null;this.vaultBoost=0;this.time=240;this.status='ready';this.invincible=0;this.stun=0;this.elapsed=0;this.message='选择角色，开始演练';this.alert=0;this.path=[];this.pathTimer=0;this.memory=0;this.interacting=false;this.chasing=false;this.lastDash=false;this.lastInteract=false;this.vaultCooldown=0;this.hunterAttackCooldown=0;this.decoding=null;this.calibration=null;this.nextCalibration=0;}
  start(){if(this.status==='ready'){this.healing=false;this.healProgress=0;this.generators[1].x=112;this.generators[1].y=25;this.generators[2].x=82;this.generators[2].y=109;this.exit.x=136;this.time=300;this.attack=null;this.status='playing';this.message='破译三台密码机，再开启东侧闸门';}}
  get powered(){return this.generators.filter(g=>g.p>=100).length;}
  startDecode(g){if(this.status!=='playing'||this.vault||this.dashRemaining>0||!this.generators.includes(g)||g.p>=100||distance(this.player,g)>=6)return false;if(this.decoding===g){this.stopDecode();return true;}this.decoding=g;this.calibration=null;this.nextCalibration=3+Math.random()*2;this.message='正在破译 · 移动可退出';return true;}
  stopDecode(){this.decoding=null;this.calibration=null;if(this.healing){this.healing=false;this.healProgress=0;}}
  failCalibration(){if(!this.calibration||!this.decoding)return;this.decoding.p=Math.max(0,this.decoding.p-10);this.alert=8;this.message='校准失败！追猎者听到了声响';this.calibration=null;this.nextCalibration=3+Math.random()*3;}
  calibrate(){if(!this.calibration||!this.decoding||this.status!=='playing')return false;const p=this.calibration.elapsed/this.calibration.duration;if(p>=.58&&p<=.76){const perfect=p>=.65&&p<=.69;this.decoding.p=Math.min(100,this.decoding.p+(perfect?6:3));this.message=perfect?'完美校准！':'校准成功';this.calibration=null;this.nextCalibration=3+Math.random()*3;return true;}this.failCalibration();return false;}
  updateDecode(dt){if(!this.decoding)return;if(distance(this.player,this.decoding)>=6){this.stopDecode();return;}if(this.calibration){this.calibration.elapsed+=dt;if(this.calibration.elapsed>=this.calibration.duration)this.failCalibration();return;}this.decoding.p=Math.min(100,this.decoding.p+dt*6);if(this.decoding.p>=100){this.message='密码机破译完成';this.alert=8;this.stopDecode();return;}this.nextCalibration-=dt;if(this.nextCalibration<=0){this.calibration={elapsed:0,duration:1.8};this.message='校准！在亮色区域点击或按空格';}}
  get nearby(){const objects=[...this.generators.filter(g=>g.p<100).map(g=>({...g,ref:g,type:'generator'})),...this.pallets.filter(p=>!p.broken).map(p=>({...p,ref:p,type:p.down?'palletVault':'pallet'})),...this.windows.map(w=>({...w,ref:w,type:'window'})),...(this.powered===3?[{...this.exit,ref:this.exit,type:'exit'}]:[])];return objects.sort((a,b)=>distance(a,this.player)-distance(b,this.player))[0];}
  blocked(x,y,r=1){return x<2||y<2||x>SIZE-2||y>SIZE-2||obstacles.some(o=>Math.hypot(x-o.x,y-o.y)<o.r+r)||walls.some(w=>Math.abs(x-w.x)<w.w/2+r&&Math.abs(y-w.y)<w.d/2+r)||this.pallets.some(p=>p.down&&Math.abs(x-p.x)<2+r&&Math.abs(y-p.y)<.5+r)||this.windows.some(w=>Math.abs(x-w.x)<2+r&&Math.abs(y-w.y)<.5+r);}
  move(actor,x,y){const n=Math.max(1,Math.ceil(Math.hypot(x,y)/.3));for(let i=0;i<n;i++){if(!this.blocked(actor.x+x/n,actor.y))actor.x+=x/n;if(!this.blocked(actor.x,actor.y+y/n))actor.y+=y/n;}if(x||y)actor.angle=Math.atan2(x,y);}
  dash(x=0,y=0){if(this.status!=='playing'||this.dashCooldown>0||this.vault)return false;if(this.characterId==='doctor'&&this.health!==1){this.message='健康时无需自愈';return false;}this.stopDecode();if(this.characterId==='doctor'){this.healing=true;this.healProgress=0;this.message='医生正在自愈 · 保持静止';}else if(this.characterId==='warden'){this.shield=2;this.message='护光展开 · 抵挡一次攻击';}else if(this.characterId==='mist'){this.smoke={x:this.player.x,y:this.player.y,time:4,r:9};this.memory=0;this.alert=0;this.message='烟幕已释放';}else{const len=Math.hypot(x,y);if(len>.1)this.player.angle=Math.atan2(x,y);this.dashDirection={x:Math.sin(this.player.angle),y:Math.cos(this.player.angle)};if(this.blocked(this.player.x+this.dashDirection.x*.4,this.player.y+this.dashDirection.y*.4))return false;this.dashRemaining=.8;this.dashFlash=.8;this.message='疾步冲刺';}this.dashCooldown=5;return true;}
  beginVault(o){if(this.vault||this.dashRemaining>0||this.vaultCooldown>0||Math.abs(this.player.x-o.x)>2.6||Math.abs(this.player.y-o.y)>3)return false;const sign=this.player.y<o.y?1:-1,to={x:o.x,y:o.y+sign*1.8};if(this.blocked(to.x,to.y,.85))return false;this.stopDecode();this.vault={from:{...this.player},to,elapsed:0,duration:1,type:o.type,boost:o.type==='window'};this.player.angle=sign>0?0:Math.PI;this.message=o.type==='window'?'翻越窗口':'翻越木板';return true;}
  visible(){if(this.smoke&&(distance(this.player,this.smoke)<this.smoke.r||distance(this.hunter,this.smoke)<this.smoke.r))return false;const d=distance(this.player,this.hunter);for(let i=0;i<=d;i+=.5){const t=i/Math.max(d,1),x=this.hunter.x+(this.player.x-this.hunter.x)*t,y=this.hunter.y+(this.player.y-this.hunter.y)*t;if(obstacles.some(o=>Math.hypot(x-o.x,y-o.y)<o.r)||walls.some(w=>Math.abs(x-w.x)<w.w/2&&Math.abs(y-w.y)<w.d/2))return false;}return true;}
  findPath(target){const n=SIZE/2,key=(x,y)=>y*n+x,start={x:Math.floor(this.hunter.x/2),y:Math.floor(this.hunter.y/2)},end={x:Math.floor(target.x/2),y:Math.floor(target.y/2)},queue=[start],seen=new Map([[key(start.x,start.y),null]]);let found=null;for(let k=0;k<queue.length;k++){const a=queue[k];if(a.x===end.x&&a.y===end.y){found=a;break;}for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const x=a.x+dx,y=a.y+dy,id=key(x,y);if(x<0||y<0||x>=n||y>=n||seen.has(id)||this.blocked(x*2+1,y*2+1,.8))continue;seen.set(id,a);queue.push({x,y});}}const path=[];while(found){path.unshift({x:found.x*2+1,y:found.y*2+1});found=seen.get(key(found.x,found.y));}return path.slice(1);}
  update(dt,input){if(this.status!=='playing')return;if(this.role==='hunter'){this.hunterInput=input;const danger=distance(this.hunter,this.player)<18;const target=danger?{x:Math.max(3,Math.min(97,this.player.x+(this.player.x-this.hunter.x)*2)),y:Math.max(3,Math.min(97,this.player.y+(this.player.y-this.hunter.y)*2))}:this.generators.find(g=>g.p<100)||this.exit;const dx=target.x-this.player.x,dy=target.y-this.player.y,l=Math.hypot(dx,dy)||1;const near=this.nearby;this.updateSimulation(dt,{x:danger||l>4?dx/l:0,y:danger||l>4?dy/l:0,interact:!danger&&l<6||danger&&near?.type==='pallet'&&distance(near,this.player)<3.5,dash:danger&&this.dashCooldown===0});}else this.updateSimulation(dt,input);}
  updateSimulation(dt,input){if(this.status!=='playing')return;this.elapsed+=dt;this.time-=dt;for(const p of ['invincible','stun','alert','dashCooldown','dashFlash','shield','vaultBoost','vaultCooldown','hunterAttackCooldown'])this[p]=Math.max(0,this[p]-dt);if(this.smoke){this.smoke.time-=dt;if(this.smoke.time<=0)this.smoke=null;}this.pallets.forEach(p=>p.drop=Math.max(0,p.drop-dt));this.unstick(this.hunter);let {x=0,y=0}=input,len=Math.hypot(x,y);if(len>1){x/=len;y/=len;}if(input.dash&&!this.lastDash)this.dash(x,y);this.lastDash=!!input.dash;
    if(this.healing){if(len>.1||this.health!==1||this.vault||this.dashRemaining>0){this.healing=false;this.healProgress=0;}else{this.healProgress=Math.min(100,this.healProgress+dt*100/3);if(this.healProgress>=100){this.health=2;this.healing=false;this.healProgress=0;this.message='自愈完成';}}}
    const locked=!!this.vault||this.dashRemaining>0||this.healing;
    if(this.vault){const v=this.vault;v.elapsed=Math.min(v.duration,v.elapsed+dt);const t=v.elapsed/v.duration,s=t*t*(3-2*t);this.player.x=v.from.x+(v.to.x-v.from.x)*s;this.player.y=v.from.y+(v.to.y-v.from.y)*s;if(t>=1){this.vault=null;this.vaultCooldown=.2;if(v.boost)this.vaultBoost=2;}}
    else if(this.dashRemaining>0){const step=Math.min(dt,this.dashRemaining),d=this.dashDirection,n=Math.ceil(step*26/.2);for(let i=0;i<n;i++){const nx=this.player.x+d.x*step*26/n,ny=this.player.y+d.y*step*26/n;if(this.blocked(nx,ny)){this.dashRemaining=0;break;}this.player.x=nx;this.player.y=ny;}this.dashRemaining=Math.max(0,this.dashRemaining-step);if(this.dashRemaining<.00001)this.dashRemaining=0;}
    else{if(this.decoding&&len>.1)this.stopDecode();const speed=(this.invincible>0?18:this.health===1?9:10)*(this.vaultBoost>0?1.3:1);this.move(this.player,x*speed*dt,y*speed*dt);}
    this.updateDecode(dt);const near=this.nearby,interaction=!!input.interact;this.interacting=false;if(!locked&&interaction&&near&&distance(near,this.player)<6){this.interacting=true;if(near.type==='pallet'&&!this.lastInteract&&distance(near,this.player)<3.5){near.ref.down=true;near.ref.drop=.4;this.message='放下木板';if(distance(near,this.hunter)<4){this.stun=3;this.message='木板命中！';}this.pathTimer=0;}else if((near.type==='window'||near.type==='palletVault')&&!this.lastInteract)this.beginVault(near);else if(len<.1&&near.type==='heal'){this.healProgress=Math.min(100,this.healProgress+dt*12.5);if(this.healProgress>=100){this.health=2;this.healProgress=0;this.message='包扎完成';}}else if(near.type==='generator'&&!this.lastInteract)this.startDecode(near.ref);else if(len<.1&&near.type==='exit'){near.ref.p=Math.min(100,near.ref.p+dt*25);if(near.ref.p===100)this.message='闸门已开启';}}this.lastInteract=interaction;
    const d=distance(this.player,this.hunter),hidden=this.smoke&&distance(this.player,this.smoke)<this.smoke.r;if(!hidden&&((d<30&&this.visible())||this.alert>0))this.memory=5;else this.memory=Math.max(0,this.memory-dt);if(hidden)this.memory=0;this.chasing=this.memory>0;const target=this.chasing?this.player:{x:50+34*Math.sin(this.elapsed*.07),y:50+30*Math.cos(this.elapsed*.07)};this.pathTimer-=dt;if(this.pathTimer<=0){this.path=this.findPath(target);this.pathTimer=.65;}
    this.updateAttack(dt);
    if(this.stun===0&&!this.attack&&this.role!=='hunter'){const pallet=this.pallets.find(p=>p.down&&!p.broken&&distance(p,this.hunter)<4);if(pallet){this.hunter.angle=Math.atan2(pallet.x-this.hunter.x,pallet.y-this.hunter.y);this.beginAttack();}else if(d<3.5&&this.visible()){this.hunter.angle=Math.atan2(this.player.x-this.hunter.x,this.player.y-this.hunter.y);this.beginAttack();}else{let next=this.path[0]||target;if(distance(next,this.hunter)<1){this.path.shift();next=this.path[0]||target;}const dx=next.x-this.hunter.x,dy=next.y-this.hunter.y,l=Math.hypot(dx,dy)||1;this.move(this.hunter,dx/l*dt*(this.chasing?11.2:6),dy/l*dt*(this.chasing?11.2:6));}}
    if(this.role==='hunter'&&this.stun===0&&!this.attack){const h=this.hunterInput||{},l=Math.hypot(h.x||0,h.y||0)||1;this.move(this.hunter,(h.x||0)/Math.max(1,l)*11.2*dt,(h.y||0)/Math.max(1,l)*11.2*dt);if(h.dash||h.interact)this.beginAttack();}
    if(this.role==='hunter'&&this.calibration&&this.calibration.elapsed/this.calibration.duration>=.65)this.calibrate();
    if(this.exit.p>=100&&this.player.x>this.exit.x-2&&Math.abs(this.player.y-this.exit.y)<8){this.status='won';this.message='成功逃离雾港';}if(this.time<=0){this.time=0;this.status='lost';this.message='时间耗尽';}
  }
}
