export const SIZE = 100;
export const distance = (a,b) => Math.hypot(a.x-b.x,a.y-b.y);
export const obstacles = [
  ...[[12,12],[23,17],[43,12],[66,12],[84,14],[12,38],[36,34],[61,30],[86,35],[18,62],[42,59],[67,63],[87,70],[12,87],[38,86],[62,88],[83,91]].map(([x,y],i)=>({x,y,r:2.8,type:'tree',h:7+i%4})),
  ...[[31,48],[55,46],[76,51],[29,76]].map(([x,y])=>({x,y,r:3.5,type:'ruin',h:4}))
];
export class Game {
  constructor(){this.reset();}
  reset(){this.player={x:48,y:73,angle:0};this.hunter={x:12,y:20,angle:0};this.generators=[{x:20,y:44,p:0},{x:73,y:23,p:0},{x:76,y:78,p:0}];this.pallets=[{x:45,y:46,down:false},{x:65,y:72,down:false},{x:30,y:28,down:false}];this.windows=[{x:51,y:27},{x:24,y:69},{x:79,y:57}];this.exit={x:96,y:50,p:0};this.stamina=100;this.health=2;this.healProgress=0;this.dashCooldown=0;this.dashFlash=0;this.dashBoost=0;this.dashCover=0;this.time=240;this.status='ready';this.invincible=0;this.stun=0;this.elapsed=0;this.message='选择视角，开始演练';this.alert=0;this.path=[];this.pathTimer=0;this.memory=0;this.interacting=false;this.chasing=false;this.lastDash=false;this.lastInteract=false;this.vaultCooldown=0;this.hunterAttackCooldown=0;this.decoding=null;this.calibration=null;this.nextCalibration=0;}
  start(){if(this.status==='ready'){this.status='playing';this.message='修理三台发电机，再开启东侧闸门';}}
  get powered(){return this.generators.filter(g=>g.p>=100).length;}
  startDecode(generator){if(this.status!=='playing'||!this.generators.includes(generator)||generator.p>=100||distance(this.player,generator)>=6)return false;if(this.decoding===generator){this.stopDecode();return true;}this.decoding=generator;this.calibration=null;this.nextCalibration=3+Math.random()*2;this.message='正在破译 · 移动可退出';return true;}
  stopDecode(){this.decoding=null;this.calibration=null;}
  failCalibration(){if(!this.calibration)return;this.decoding.p=Math.max(0,this.decoding.p-10);this.alert=8;this.message='校准失败！追猎者听到了声响';this.calibration=null;this.nextCalibration=3+Math.random()*3;}
  calibrate(){if(!this.calibration||!this.decoding||this.status!=='playing')return false;const position=this.calibration.elapsed/this.calibration.duration;if(position>=.58&&position<=.76){const perfect=position>=.65&&position<=.69;this.decoding.p=Math.min(100,this.decoding.p+(perfect?6:3));this.message=perfect?'完美校准！':'校准成功';this.calibration=null;this.nextCalibration=3+Math.random()*3;return true;}this.failCalibration();return false;}
  updateDecode(dt){if(!this.decoding)return;if(distance(this.player,this.decoding)>=6||this.decoding.p>=100){this.stopDecode();return;}if(this.calibration){this.calibration.elapsed+=dt;if(this.calibration.elapsed>=this.calibration.duration)this.failCalibration();return;}this.decoding.p=Math.min(100,this.decoding.p+dt*6);if(this.decoding.p>=100){this.message='密码机破译完成';this.alert=8;this.stopDecode();return;}this.nextCalibration-=dt;if(this.nextCalibration<=0){this.calibration={elapsed:0,duration:1.8};this.message='校准！在亮色区域点击或按空格';}}
  get nearby(){const choices=[...this.generators.filter(g=>g.p<100).map(g=>({...g,ref:g,type:'generator'})),...this.pallets.filter(p=>!p.down).map(p=>({...p,ref:p,type:'pallet'})),...this.windows.map(w=>({...w,ref:w,type:'window'})),...(this.health===1?[{x:this.player.x,y:this.player.y,ref:this,type:'heal'}]:[]),...(this.powered===3?[{...this.exit,ref:this.exit,type:'exit'}]:[])];return choices.filter(o=>o.type!=='heal'||!choices.some(other=>other.type!=='heal'&&distance(other,this.player)<6)).sort((a,b)=>distance(a,this.player)-distance(b,this.player))[0];}
  blocked(x,y,r=1){return x<2||y<2||x>98||y>98||obstacles.some(o=>Math.hypot(x-o.x,y-o.y)<o.r+r)||this.pallets.some(p=>p.down&&Math.abs(x-p.x)<3+r&&Math.abs(y-p.y)<.8+r)||this.windows.some(w=>Math.abs(x-w.x)<2.4+r&&Math.abs(y-w.y)<.8+r);}
  move(actor,x,y){if(!this.blocked(actor.x+x,actor.y))actor.x+=x;if(!this.blocked(actor.x,actor.y+y))actor.y+=y;if(x||y)actor.angle=Math.atan2(x,y);}
  dash(x,y){if(this.status!=='playing'||this.dashCooldown>0)return false;const length=Math.hypot(x,y);if(length<.1){x=Math.sin(this.player.angle);y=Math.cos(this.player.angle);}else{x/=length;y/=length;}if(!Number.isFinite(x)||!Number.isFinite(y))return false;let steps=0;for(let i=0;i<36;i++){const nx=this.player.x+x*.5,ny=this.player.y+y*.5;if(this.blocked(nx,ny,1))break;this.player.x=nx;this.player.y=ny;steps++;}if(!steps){this.message='前方有障碍，无法突进';return false;}this.stopDecode();this.player.angle=Math.atan2(x,y);this.dashCooldown=5;this.dashFlash=.45;this.dashBoost=1.2;this.dashCover=1.2;this.invincible=Math.max(this.invincible,.65);this.memory=0;this.alert=0;this.chasing=false;this.message='疾步突进！短暂加速并摆脱追踪';this.pathTimer=0;return true;}
  visible(){let d=distance(this.player,this.hunter);for(let i=0;i<=d;i+=1.5){let t=i/Math.max(d,1),x=this.hunter.x+(this.player.x-this.hunter.x)*t,y=this.hunter.y+(this.player.y-this.hunter.y)*t;if(obstacles.some(o=>Math.hypot(x-o.x,y-o.y)<o.r)||this.pallets.some(p=>p.down&&Math.abs(x-p.x)<3&&Math.abs(y-p.y)<.8))return false;}return true;}
  findPath(target){const n=25,key=(x,y)=>y*n+x,start={x:Math.floor(this.hunter.x/4),y:Math.floor(this.hunter.y/4)},end={x:Math.floor(target.x/4),y:Math.floor(target.y/4)},queue=[start],seen=new Map([[key(start.x,start.y),null]]);let found=null;for(let k=0;k<queue.length;k++){const a=queue[k];if(a.x===end.x&&a.y===end.y){found=a;break;}for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){let x=a.x+dx,y=a.y+dy,id=key(x,y);if(x<0||y<0||x>=n||y>=n||seen.has(id)||this.blocked(x*4+2,y*4+2,1.2))continue;seen.set(id,a);queue.push({x,y});}}let path=[];while(found){path.unshift({x:found.x*4+2,y:found.y*4+2});found=seen.get(key(found.x,found.y));}return path.slice(1);}
  update(dt,input){if(this.status!=='playing')return;this.elapsed+=dt;this.time-=dt;for(const prop of ['invincible','stun','alert','dashCooldown','dashFlash','dashBoost','dashCover','vaultCooldown','hunterAttackCooldown'])this[prop]=Math.max(0,this[prop]-dt);let {x=0,y=0}=input,len=Math.hypot(x,y);if(len>1){x/=len;y/=len;len=1;}if(input.dash&&!this.lastDash)this.dash(x,y);this.lastDash=!!input.dash;
    if(this.decoding&&len>.1)this.stopDecode();
    const sprint=input.sprint&&this.stamina>5&&len>0;this.stamina=Math.max(0,Math.min(100,this.stamina+(sprint?-26:16)*dt));const speed=this.dashBoost>0?22:this.invincible>0?18:sprint?16:this.health===1?9:10;this.move(this.player,x*speed*dt,y*speed*dt);
    this.updateDecode(dt);
    const near=this.nearby,interaction=!!input.interact;this.interacting=false;if(interaction&&near&&distance(near,this.player)<6){this.interacting=true;if(near.type==='pallet'&&!this.lastInteract){near.ref.down=true;this.message='木板已放下';if(distance(near,this.hunter)<9){this.stun=3;this.message='命中！追猎者眩晕 3 秒';}this.pathTimer=0;}else if(near.type==='window'&&!this.lastInteract&&this.vaultCooldown===0){let sign=this.player.y<near.y?1:-1,landing={x:near.x,y:near.y+sign*5};if(!this.blocked(landing.x,landing.y,1)){this.player.x=landing.x;this.player.y=landing.y;this.vaultCooldown=1.2;this.message='翻越窗口';this.alert=3;this.pathTimer=0;}}else if(len<.1&&near.type==='heal'){this.healProgress=Math.min(100,this.healProgress+dt*12.5);if(this.healProgress>=100){this.health=2;this.healProgress=0;this.message='包扎完成，恢复健康';}}else if(near.type==='generator'&&!this.lastInteract){this.startDecode(near.ref);}else if(len<.1&&near.type==='exit'){near.ref.p=Math.min(100,near.ref.p+dt*25);if(near.ref.p===100)this.message='闸门已开启，走出东侧出口！';}}this.lastInteract=interaction;
    const d=distance(this.player,this.hunter);if(((d<30&&this.visible())||this.alert>0)&&(this.dashCover===0||d<8))this.memory=5;else this.memory=Math.max(0,this.memory-dt);this.chasing=this.memory>0;let target=this.chasing?this.player:{x:50+34*Math.sin(this.elapsed*.07),y:50+30*Math.cos(this.elapsed*.07)};this.pathTimer-=dt;if(this.pathTimer<=0){this.path=this.findPath(target);this.pathTimer=.65;}if(this.stun===0){let next=this.path[0]||target;if(distance(next,this.hunter)<2){this.path.shift();next=this.path[0]||target;}let dx=next.x-this.hunter.x,dy=next.y-this.hunter.y,l=Math.hypot(dx,dy)||1;this.move(this.hunter,dx/l*dt*(this.chasing?11.2:6),dy/l*dt*(this.chasing?11.2:6));}
    if(distance(this.player,this.hunter)<2.8&&this.invincible===0&&this.stun===0&&this.hunterAttackCooldown===0){this.stopDecode();this.health--;this.healProgress=0;this.invincible=3;this.hunterAttackCooldown=3;this.message=this.health?'受伤！短暂加速，可按住 E 包扎':'你已倒地';if(this.health<=0)this.status='lost';}if(this.exit.p>=100&&this.player.x>94&&Math.abs(this.player.y-50)<8){this.status='won';this.message='成功逃离雾港';}if(this.time<=0){this.time=0;this.status='lost';this.message='时间耗尽，逃脱失败';}
  }
}
