import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Game,walls} from './game.js';
const idle={x:0,y:0,interact:false,dash:false};
function safe(){const g=new Game();g.start();g.stun=100;g.hunter={x:5,y:5};return g;}
test('ready state freezes and reset retains character selection',()=>{const g=new Game();g.selectCharacter('mist');g.update(1,idle);assert.equal(g.time,240);g.start();assert.equal(g.selectCharacter('courier'),false);g.reset();assert.equal(g.characterId,'mist');});
test('continuous decoding needs a single click',()=>{const g=safe();g.player={x:20,y:44};assert.ok(g.startDecode(g.generators[0]));g.update(1,idle);assert.equal(g.generators[0].p,6);g.update(.1,{...idle,x:1});assert.equal(g.decoding,null);});
test('calibration succeeds and failure alerts hunter',()=>{const g=safe();g.player={x:20,y:44};g.startDecode(g.generators[0]);g.calibration={elapsed:1.8*.67,duration:1.8};assert.ok(g.calibrate());assert.equal(g.generators[0].p,6);g.calibration={elapsed:0,duration:1.8};assert.equal(g.calibrate(),false);assert.equal(g.alert,8);});
test('dash is continuous not teleportation and ends against a wall',()=>{const g=safe();g.player={x:50,y:50,angle:0};assert.ok(g.dash(0,-1));assert.equal(g.player.y,50);g.update(.1,idle);assert.ok(Math.abs(g.player.y-47.4)<.001);assert.equal(g.dashCooldown,4.9);g.update(.7,idle);assert.equal(g.dashRemaining,0);g.update(5,idle);assert.equal(g.dashCooldown,0);g.player={x:40,y:33,angle:Math.PI/2};g.dash(1,0);g.update(.5,idle);assert.ok(g.player.x<41);assert.equal(g.dashRemaining,0);});
test('normal movement ignores removed sprint input',()=>{const a=safe(),b=safe();a.update(.1,{...idle,x:1});b.update(.1,{...idle,x:1,sprint:true});assert.equal(a.player.x,b.player.x);});
test('window vault takes one second and has a short landing and two second boost',()=>{const g=safe();g.player={x:51,y:25.2,angle:0};assert.ok(g.beginVault({...g.windows[0],type:'window'}));assert.equal(g.player.y,25.2);g.update(.5,idle);assert.ok(g.vault);assert.ok(Math.abs(g.player.y-27)<.001);g.update(.5,idle);assert.equal(g.vault,null);assert.ok(Math.abs(g.player.y-28.8)<.001);assert.equal(g.vaultBoost,2);const x=g.player.x;g.update(.1,{...idle,x:1});assert.ok(Math.abs(g.player.x-x-1.3)<.001);g.update(2,idle);assert.equal(g.vaultBoost,0);});
test('dropped pallet can be vaulted and window openings fit the wall',()=>{const g=safe();g.player={x:50,y:37.2};g.update(.01,{...idle,interact:true});assert.equal(g.pallets[0].down,true);g.update(.01,idle);g.update(.01,{...idle,interact:true});assert.ok(g.vault);assert.equal(g.vault.type,'palletVault');assert.ok(walls.length>10);assert.equal(g.blocked(45,27),true);assert.equal(g.blocked(51,25.2),false);});
test('warden shield consumes a timed hit without losing health',()=>{const g=new Game();g.selectCharacter('warden');g.start();g.player={x:50,y:50,angle:0};g.hunter={x:50,y:50};g.dash();g.update(.01,idle);assert.equal(g.health,2);g.update(.55,idle);assert.equal(g.health,2);assert.equal(g.shield,0);assert.equal(g.attack.phase,'recovery');});
test('mist skill breaks tracking inside smoke',()=>{const g=new Game();g.selectCharacter('mist');g.start();g.player={x:50,y:50,angle:0};g.hunter={x:50,y:60};g.memory=5;g.dash();g.update(.01,idle);assert.equal(g.chasing,false);assert.ok(g.smoke);assert.equal(g.dashCooldown,4.99);});
test('exit and timer still end the match',()=>{const g=safe();g.generators.forEach(m=>m.p=100);g.player={x:g.exit.x-1,y:50};g.exit.p=99;g.update(.1,{...idle,interact:true});assert.equal(g.status,'won');g.reset();g.start();g.time=.01;g.update(.1,idle);assert.equal(g.status,'lost');});
test('only doctor heals using a five second cooldown skill',()=>{const g=safe();g.characterId='doctor';g.health=1;assert.ok(g.dash());assert.equal(g.dashCooldown,5);g.update(3,idle);assert.equal(g.health,2);g.health=1;g.dashCooldown=0;g.dash();g.update(.1,{...idle,x:1});assert.equal(g.healing,false);g.characterId='courier';g.update(8,{...idle,interact:true});assert.equal(g.health,1);});
test('hunter escapes dropped pallet and destroys it with a timed strike',()=>{const g=safe();g.stun=0;const p=g.pallets[0];p.down=true;g.hunter={x:p.x,y:p.y};g.unstick(g.hunter);assert.equal(g.blocked(g.hunter.x,g.hunter.y),false);g.hunter.angle=Math.atan2(p.x-g.hunter.x,p.y-g.hunter.y);g.breakPallet();assert.equal(p.broken,undefined);g.updateAttack(.55);assert.equal(p.broken,true);assert.equal(g.attack.phase,'recovery');});
test('hunter role movement stops during attack windup and recovery',()=>{const g=new Game();g.selectRole('hunter');g.start();g.player={x:80,y:80};g.hunter={x:50,y:50};g.update(.1,{...idle,x:1});assert.ok(Math.abs(g.hunter.x-51.12)<.001);g.update(.1,{...idle,dash:true});assert.equal(g.attack.phase,'windup');const x=g.hunter.x;g.update(.3,{...idle,x:1});assert.equal(g.hunter.x,x);g.update(.3,idle);assert.equal(g.attack.phase,'recovery');});
test('holding interaction after dropping a pallet does not auto vault',()=>{const g=safe();g.player={x:50,y:37.2};g.update(.01,{...idle,interact:true});for(let i=0;i<12;i++)g.update(.1,{...idle,interact:true});assert.equal(g.pallets[0].down,true);assert.equal(g.vault,null);});
