export const SIZE = 100;
export const distance = (a,b) => Math.hypot(a.x-b.x,a.y-b.y);
export const obstacles = [
  ...[[12,12],[23,17],[43,12],[66,12],[84,14],[12,38],[36,34],[61,30],[86,35],[18,62],[42,59],[67,63],[87,70],[12,87],[38,86],[62,88],[83,91]].map(([x,y],i)=>({x,y,r:2.8,type:'tree',h:7+i%4})),
  ...[[31,48],[55,46],[76,51],[29,76]].map(([x,y])=>({x,y,r:3.5,type:'ruin',h:4}))
];
export class Game {
  constructor(){this.reset();}
  reset(){this.player={x:48,y:73,angle:0};this.hunter={x:12,y:20,angle:0};this.generators=[{x:20,y:44,p:0},{x:73,y:23,p:0},{x:76,y:78,p:0}];this.pallets=[{x:45,y:46,down:false},{x:65,y:72,down:false},{x:30,y:28,down:false}];this.exit={x:96,y:50,p:0};this.stamina=100;this.health=2;this.time=240;this.status='ready';this.invincible=0;this.stun=0;this.elapsed=0;this.message='选择视角，开始演练';this.alert=0;this.path=[];this.pathTimer=0;this.memory=0;}
  start(){if(this.status==='ready'){this.status='playing';this.message='修理三台发电机，再开启东侧闸门';}}
  get powered(){return this.generators.filter(g=>g.p>=100).length;}
  get nearby(){return [...this.generators.filter(g=>g.p<100).map(g=>({...g,ref:g,type:'generator'})),...this.pallets.filter(p=>!p.down).map(p=>({...p,ref:p,type:'pallet'})),...(this.powered===3?[{...this.exit,ref:this.exit,type:'exit'}]:[])].sort((a,b)=>distance(a,this.player)-distance(b,this.player))[0];}
  blocked(x,y,r=1){return x<2||y<2||x>98||y>98||obstacles.some(o=>Math.hypot(x-o.x,y-o.y)<o.r+r)||this.pallets.some(p=>p.down&&Math.abs(x-p.x)<3+r&&Math.abs(y-p.y)<.8+r);}
  move(actor,x,y){if(!this.blocked(actor.x+x,actor.y))actor.x+=x;if(!this.blocked(actor.x,actor.y+y))actor.y+=y;if(x||y)actor.angle=Math.atan2(x,y);}
  visible(){let d=distance(this.player,this.hunter);for(let i=0;i<=d;i+=1.5){let t=i/Math.max(d,1);if(obstacles.some(o=>Math.hypot(this.hunter.x+(this.player.x-this.hunter.x)*t-o.x,this.hunter.y+(this.player.y-this.hunter.y)*t-o.y)<o.r))return false;}return true;}
  findPath(target){const n=25,key=(x,y)=>y*n+x,start={x:Math.floor(this.hunter.x/4),y:Math.floor(this.hunter.y/4)},end={x:Math.floor(target.x/4),y:Math.floor(target.y/4)},queue=[start],seen=new Map([[key(start.x,start.y),null]]);let found=null;for(let k=0;k<queue.length;k++){const a=queue[k];if(a.x===end.x&&a.y===end.y){found=a;break;}for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){let x=a.x+dx,y=a.y+dy,id=key(x,y);if(x<0||y<0||x>=n||y>=n||seen.has(id)||this.blocked(x*4+2,y*4+2,1.2))continue;seen.set(id,a);queue.push({x,y});}}let path=[];while(found){path.unshift({x:found.x*4+2,y:found.y*4+2});found=seen.get(key(found.x,found.y));}return path.slice(1);}
  update(dt,input){if(this.status!=='playing')return;this.elapsed+=dt;this.time-=dt;this.invincible=Math.max(0,this.invincible-dt);this.stun=Math.max(0,this.stun-dt);this.alert=Math.max(0,this.alert-dt);let {x,y}=input,len=Math.hypot(x,y);if(len>1){x/=len;y/=len;}let sprint=input.sprint&&this.stamina>5&&len>0;this.stamina=Math.max(0,Math.min(100,this.stamina+(sprint?-26:16)*dt));const speed=this.invincible>0?18:sprint?16:10;this.move(this.player,x*speed*dt,y*speed*dt);
    let near=this.nearby;this.interacting=false;if(input.interact&&near&&distance(near,this.player)<6){this.interacting=true;if(near.type==='pallet'){near.ref.down=true;this.message='木板已放下';if(distance(near,this.hunter)<9){this.stun=3;this.message='命中！追猎者眩晕 3 秒';}this.pathTimer=0;}else if(len<.1){near.ref.p=Math.min(100,near.ref.p+dt*(near.type==='exit'?25:14));if(near.ref.p===100){this.message=near.type==='exit'?'闸门已开启，走出东侧出口！':'发电机已启动';if(near.type==='generator')this.alert=8;}}}
    const d=distance(this.player,this.hunter);if(d<30&&this.visible()||this.alert>0)this.memory=5;else this.memory=Math.max(0,this.memory-dt);this.chasing=this.memory>0;let target=this.chasing?this.player:{x:50+34*Math.sin(this.elapsed*.07),y:50+30*Math.cos(this.elapsed*.07)};this.pathTimer-=dt;if(this.pathTimer<=0){this.path=this.findPath(target);this.pathTimer=.65;}if(this.stun===0){let next=this.path[0]||target;if(distance(next,this.hunter)<2){this.path.shift();next=this.path[0]||target;}let dx=next.x-this.hunter.x,dy=next.y-this.hunter.y,l=Math.hypot(dx,dy)||1;this.move(this.hunter,dx/l*dt*(this.chasing?11.2:6),dy/l*dt*(this.chasing?11.2:6));}
    if(d<2.8&&this.invincible===0&&this.stun===0){this.health--;this.invincible=3;this.message=this.health?'受伤！短暂加速，尽快脱离追击':'你已倒地';if(this.health<=0)this.status='lost';}if(this.exit.p>=100&&this.player.x>94&&Math.abs(this.player.y-50)<8){this.status='won';this.message='成功逃离雾港';}if(this.time<=0){this.time=0;this.status='lost';this.message='时间耗尽，逃脱失败';}
  }
}
