import {distance} from './game.js';
function inside(p,polygon){let result=false;for(let i=0,j=polygon.length-1;i<polygon.length;j=i++){const a=polygon[i],b=polygon[j];if((a.y>p.y)!==(b.y>p.y)&&p.x<(b.x-a.x)*(p.y-a.y)/(b.y-a.y)+a.x)result=!result;}return result;}
export class HunterSkills{
  constructor(){this.cooldown=0;this.rocket=0;this.projectiles=[];this.trail=[];this.zones=[];this.lastHeld=false;this.humidity=new Map();}
  damage(a){if(a.eliminated||a.escaped||a.seated!=null||a.sim.health<=0||a.sim.invincible>0)return false;if(a.sim.shield>0){a.sim.shield=0;return true;}a.sim.health=Math.max(0,a.sim.health-1);a.sim.player.health=a.sim.health;a.sim.invincible=3;a.sim.stopDecode();return true;}
  update(match,hunter,input,dt){const g=hunter.sim,pos=g.hunter,targets=match.actors.filter(a=>a.role==='survivor');this.cooldown=Math.max(0,this.cooldown-dt);const held=!!input.skill;
    if(hunter.character==='smiley'){if(held&&!this.lastHeld&&this.cooldown===0&&g.stun===0&&!g.attack)this.rocket=10;if(this.rocket>0){if(!held||g.stun>0){this.rocket=0;this.cooldown=5;}else{this.rocket=Math.max(0,this.rocket-dt);const len=Math.hypot(input.x||0,input.y||0);if(len>.1)pos.angle=Math.atan2(input.x,input.y);const before={...pos};g.move(pos,Math.sin(pos.angle)*26*dt,Math.cos(pos.angle)*26*dt);const hit=targets.find(a=>Math.abs((a.sim.player.z||0)-(pos.z||0))<1.5&&distance(a.sim.player,pos)<2.8&&this.damage(a));if(hit||distance(before,pos)<dt*4||this.rocket===0){this.rocket=0;this.cooldown=5;g.message=hit?'火箭冲刺命中':'火箭冲刺结束';}}}}
    if(hunter.character==='ripper'&&held&&!this.lastHeld&&this.cooldown===0&&g.stun===0&&!g.attack){this.projectiles.push({x:pos.x,y:pos.y,z:pos.z||0,angle:pos.angle||0,remaining:72});this.cooldown=5;g.message='雾刃已发射';}
    for(const p of this.projectiles){let alive=true;const steps=Math.ceil(30*dt/.2);for(let i=0;i<steps;i++){const step=30*dt/steps;p.x+=Math.sin(p.angle)*step;p.y+=Math.cos(p.angle)*step;p.remaining-=step;g.collisionHeight=p.z;if(g.blocked(p.x,p.y,.2)){alive=false;break;}const a=targets.find(a=>Math.abs((a.sim.player.z||0)-p.z)<1.5&&distance(a.sim.player,p)<1.1&&this.damage(a));if(a){alive=false;break;}}g.collisionHeight=0;if(!alive)p.remaining=0;}this.projectiles=this.projectiles.filter(p=>p.remaining>0);
    if(hunter.character==='naiad'){const now=300-match.time;this.trail=this.trail.filter(p=>p.until>now);const last=this.trail.at(-1);if(!last||distance(last,pos)>.7){const point={x:pos.x,y:pos.y,z:pos.z||0,until:now+15,expires:999};const close=this.trail.findIndex((p,i)=>i<this.trail.length-8&&distance(p,point)<1.4&&Math.abs(p.z-point.z)<1);if(close>=0){const polygon=[...this.trail.slice(close),point];let area=0;for(let i=0;i<polygon.length;i++){const a=polygon[i],b=polygon[(i+1)%polygon.length];area+=a.x*b.y-b.x*a.y;}if(Math.abs(area)>12){this.zones.push({polygon,time:15,z:point.z});this.trail=[];}}this.trail.push(point);}for(const a of targets){const wet=this.trail.some(p=>Math.abs(p.z-(a.sim.player.z||0))<1&&distance(p,a.sim.player)<1.3)||this.zones.some(z=>Math.abs(z.z-(a.sim.player.z||0))<1&&inside(a.sim.player,z.polygon));let humidity=this.humidity.get(a.id)||0;humidity=Math.max(0,Math.min(100,humidity+dt*(wet?25:-8)));if(humidity>=100){this.damage(a);humidity=0;}this.humidity.set(a.id,humidity);}}
    this.zones.forEach(z=>z.time-=dt);this.zones=this.zones.filter(z=>z.time>0);this.lastHeld=held;
  }
  snapshot(){return {cooldown:this.cooldown,rocket:this.rocket,projectiles:this.projectiles,trail:this.trail,zones:this.zones,humidity:Object.fromEntries(this.humidity)};}
}
