import {Game,distance} from './game.js';
import {HunterBrain,sightClear} from './hunter-ai.js';
import {ChairSystem} from './chairs.js';

export class SharedMatch{
  constructor(roster,fillBots){
    this.world=new Game();this.world.start();this.time=300;this.status='playing';
    const members=[...roster];if(!members.some(p=>p.role==='hunter'))members.push({id:'bot-hunter',nickname:'人机监管者',role:'hunter',character:'ripper',bot:true});
    if(fillBots)while(members.filter(p=>p.role==='survivor').length<4)members.push({id:'bot-'+members.length,nickname:'人机求生者 '+members.length,role:'survivor',character:'mercenary',bot:true});
    let index=0;this.actors=members.map(p=>{const sim=new Game();sim.characterId=p.role==='survivor'?p.character:'mercenary';sim.hunterId=p.role==='hunter'?p.character:'ripper';sim.start();const pos=p.role==='hunter'?{x:48,y:65}: {x:40+index++*4,y:70};Object.assign(p.role==='hunter'?sim.hunter:sim.player,pos);sim.generators=this.world.generators;sim.pallets=this.world.pallets;sim.exits=this.world.exits;sim.exit=this.world.exit;return {...p,sim,input:{x:0,y:0},seen:0};});
    this.tick=0;this.hunterBrain=new HunterBrain();this.chairSystem=new ChairSystem();
  }
  input(id,input){const a=this.actors.find(a=>a.id===id&&!a.bot);if(!a)return;a.input={x:Math.max(-1,Math.min(1,Number(input.x)||0)),y:Math.max(-1,Math.min(1,Number(input.y)||0)),interact:!!input.interact,dash:!!input.dash};a.seen=this.tick;}
  action(id,action,index){const a=this.actors.find(a=>a.id===id&&!a.bot);if(!a||a.role!=='survivor')return;if(action==='decode')a.sim.startDecode(this.world.generators[index]);if(action==='calibrate')a.sim.calibrate();}
  chairSnapshot(){return {result:this.result,chairs:this.chairSystem.chairs,carried:this.chairSystem.carried,rescues:[...this.chairSystem.rescues].map(([id,r])=>({id,...r})),actors:this.actors.map(a=>({id:a.id,seated:a.seated,eliminated:!!a.eliminated,nextChair:a.nextChair||0}))};}
  update(dt=.05){if(this.status!=='playing')return;this.tick++;this.time-=dt;const hunter=this.actors.find(a=>a.role==='hunter'),survivors=this.actors.filter(a=>a.role==='survivor');
    for(const a of survivors){const g=a.sim;if(a.eliminated||a.escaped||a.seated!=null||this.chairSystem.carried===a.id)continue;if(g.health<=0){if(this.tick-a.seen<=10&&!a.bot)g.move(g.player,(a.input.x||0)*2*dt,(a.input.y||0)*2*dt);continue;}Object.assign(g.hunter,hunter.sim.hunter);g.aiHunterDisabled=true;g.stun=999;g.attack=null;g.status='playing';let input=a.input;if(a.bot){const occupied=this.chairSystem.chairs.find(c=>c.occupant);const target=occupied||this.world.generators.find(m=>m.p<100)||this.world.exits[0],d=distance(g.player,hunter.sim.hunter),rescue=!!occupied,dx=d<12&&!rescue?g.player.x-hunter.sim.hunter.x:target.x-g.player.x,dy=d<12&&!rescue?g.player.y-hunter.sim.hunter.y:target.y-g.player.y,l=Math.hypot(dx,dy)||1;input={x:Math.hypot(dx,dy)>2.5?dx/l:0,y:Math.hypot(dx,dy)>2.5?dy/l:0,interact:(d>=12||rescue)&&distance(g.player,target)<3};a.input=input;if(!g.decoding&&target.p<100&&this.world.generators.includes(target)&&distance(g.player,target)<6)g.startDecode(target);if(g.calibration)g.calibration.elapsed=g.calibration.duration*.67,g.calibrate();}else if(this.tick-a.seen>10)input={x:0,y:0};
      const before=this.world.pallets.map(p=>p.down);g.updateSimulation(dt,input);if(before.some((v,i)=>!v&&this.world.pallets[i].down)&&distance(g.player,hunter.sim.hunter)<4)hunter.sim.stun=3;
      g.player.health=g.health;if(g.status==='won')a.escaped=true;
    }
    const h=hunter.sim;h.stun=Math.max(0,h.stun-dt);h.hunterAttackCooldown=Math.max(0,h.hunterAttackCooldown-dt);const targets=survivors.filter(a=>a.sim.health>0&&!a.escaped).sort((a,b)=>distance(a.sim.player,h.hunter)-distance(b.sim.player,h.hunter));let input=hunter.input;if(hunter.bot)input=this.hunterBrain.update(h,targets,dt);else if(this.tick-hunter.seen>10)input={x:0,y:0};
    const chairInteraction=this.chairSystem.carried||survivors.some(a=>a.sim.health<=0&&!a.eliminated&&a.seated==null&&distance(a.sim.player,h.hunter)<3);
    if(!h.attack&&h.stun===0){if(!(hunter.bot&&this.chairSystem.carried))h.move(h.hunter,(input.x||0)*11.2*dt,(input.y||0)*11.2*dt);if(input.dash||input.interact&&!chairInteraction)h.beginAttack(!!input.interact);}
    else if(h.attack?.phase==='windup'&&h.stun===0){const target=targets.find(a=>sightClear(h,h.hunter,a.sim.player));if(target&&hunter.bot){const dx=target.sim.player.x-h.hunter.x,dy=target.sim.player.y-h.hunter.y,d=Math.hypot(dx,dy)||1;h.hunter.angle=Math.atan2(dx,dy);h.attack.angle=h.hunter.angle;h.move(h.hunter,dx/d*Math.min(Math.max(0,d-1.65),11.2*dt),dy/d*Math.min(Math.max(0,d-1.65),11.2*dt));}else if(!hunter.bot)h.move(h.hunter,(input.x||0)*6*dt,(input.y||0)*6*dt);}
    if(h.attack){const target=targets.find(a=>h.inAttackCone(a.sim.player)&&sightClear(h,h.hunter,a.sim.player));if(target){h.player=target.sim.player;h.survivors=[h.player];h.health=target.sim.health;h.shield=target.sim.shield;h.invincible=target.sim.invincible||0;h.player.invincible=h.invincible;h.player.health=target.sim.health;const previousHealth=target.sim.health,phase=h.attack.phase;h.updateAttack(dt);if(phase==='windup'&&h.attack?.phase==='recovery'){target.sim.health=h.player.health;target.sim.shield=h.shield;target.sim.invincible=h.player.invincible||0;if(target.sim.health<previousHealth)target.sim.stopDecode();}}else{h.player={x:-1000,y:-1000,z:0};h.survivors=[];h.invincible=0;h.updateAttack(dt);}}
    for(const a of survivors){if(this.chairSystem.rescues.has(a.id)&&a.sim.health<a._previousHealth){a.sim.health=0;a.sim.player.health=0;this.chairSystem.rescues.delete(a.id);h.message='恐惧震慑';}a._previousHealth=a.sim.health;}
    this.chairSystem.update(this,dt);h.updateFalls(dt);if(this.time<=0){for(const a of survivors)if(!a.escaped&&!a.eliminated)this.chairSystem.eliminate(a);}if(this.time<=0||survivors.every(a=>a.escaped||a.eliminated)){this.status='finished';const escaped=survivors.filter(a=>a.escaped).length;this.result={escaped,eliminated:survivors.length-escaped,total:survivors.length,winner:escaped>survivors.length/2?'survivors':escaped===survivors.length/2?'draw':'hunter'};}
  }
  snapshot(){return {tick:this.tick,time:this.time,status:this.status,generators:this.world.generators,pallets:this.world.pallets,exits:this.world.exits,actors:this.actors.map(a=>{const g=a.sim;return {id:a.id,nickname:a.nickname,role:a.role,character:a.character,bot:!!a.bot,position:a.role==='hunter'?g.hunter:g.player,health:g.health,escaped:!!a.escaped,attack:a.role==='hunter'?g.attack:null,stun:g.stun,dashCooldown:g.dashCooldown,hunterAttackCooldown:g.hunterAttackCooldown,vault:g.vault,calibration:g.calibration,decodeIndex:this.world.generators.indexOf(g.decoding),shield:g.shield,healing:g.healing,healProgress:g.healProgress,message:g.message};})};}
}
